//konfigurasi ke cloudflare
name = "kost-backend"
main = "src/index.js"
compatibility_date = "2025-05-07"

[[d1_databases]]
binding = "DB"
database_name = "kost_db"
database_id = "9ff06c40-9e1a-4d3b-bc0d-25b47563384c"

[build]
command = "npm install"
